# 1. Conexión básica
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_alquileres?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Configuración JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. Forzar a que falle rápido si no conecta (para ver el error real)
spring.datasource.hikari.initialization-fail-timeout=1

# 4. Configuración del servidor de correo
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=audios311online@gmail.com
spring.mail.password=dsvs wrtl qiir kppc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true